# Generated by Django 2.1.1 on 2018-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songtypes_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
